# Controlador de Posición
position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint1
    - Joint1a
    - Joint2
    - Joint2a
    - Joint12a
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
  gains:
    Joint1: {p: 1000, i: 0, d: 100}
    Joint1a: {p: 1000, i: 0, d: 100}
    Joint2: {p: 1000, i: 0, d: 100}
    Joint2a: {p: 1000, i: 0, d: 100}
    Joint12a: {p: 1000, i: 0, d: 100}

# Controlador de Velocidad
velocity_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - Joint1
    - Joint1a
    - Joint2
    - Joint2a
    - Joint12a
  gains:
    Joint1: {p: 1000, i: 0, d: 100}
    Joint1a: {p: 1000, i: 0, d: 100}
    Joint2: {p: 1000, i: 0, d: 100}
    Joint2a: {p: 1000, i: 0, d: 100}
    Joint12a: {p: 1000, i: 0, d: 100}

